name: Rust CI/CD

on:
  push:
  pull_request:

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose

  publish-crate:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref_type == 'tag'
    steps:
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Check out code
        uses: actions/checkout@v3
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
